### ISSUE TITLE
RFC In light of puppeteer overlapping this library, does it make sense to maintain?

### ISSUE THREAD

**Issue by krisselden** [devtrace/chrome-debugging-client#14]
I'm thinking of migrating my chrome-tracing benchmark runner to puppeteer since it pretty much overlaps every use case I had for creating this library.

The only doubts I have is using typescript + no-floating-promises tslint has made this very solid for not deadlocking.  I'm a bit nervous about giving that part up.

@paulirish thoughts on if it is still worth maintaining this given puppeteer?

**Comment by Bnaya** [comment]
I would love to see this library keeps going
IMO puppeteer can/should use this excellent lower-level library, and just give a higher level api

**Comment by EliSnow** [comment]
My biggest reason for using this over libraries was I need direct access to the underlying websocket to issue CDP commands. Additionally, I chose chrome-debugging-client because of the TypeScript typings. I'm not sure if puppeteer has typings and if they allow direct access to websocket to issue protocol level commands. If they do, I wouldn't mind transitioning.

**Comment by krisselden** [comment]
@EliSnow so it isn't publicly exposed it is on the browser instances as `browser._connection`

Declaration files could be added.  We could lobby exposing the ability to send() commands in puppeteer.  I just don't see this project ever taking off with official competition from GoogleChrome.

I would love it if they used typescript instead, no-floating-promises with tslint is a big deal for async/await projects.

**Comment by EliSnow** [comment]
I did look and there are typings for Puppeteer, which is awesome. It seems the Puppeteer folks have instrumented their code with JSDoc annotations which allow the typings to be auto-generated.

The real value that chrome-debugging-client provides to me is the auto-generated typings for the underlying Chrome DevTools Protocol. That is really powerful. My particular use case is to remote control chrome to navigate various pages, grab a myriad of performance metrics (like WebPageTest), generate a video of each page load and upload the results to a repository. I'm not doing much more than navigating to a page, but puppeteer does not provide me access to all of the powerful data provided from the CDP. I'm sure I could create issues in Puppeteer or provide them PRs, but I already get the functionality just by having access to the protocol.

That said, I totally understand your point. Honestly I wouldn't mind if all chrome-debugging-client provided was the auto-generated typings for the protocol. If I could take that and couple it with puppeteer, I would be happy.

Perhaps it would be appropriate to open an issue with Puppeteer, have a discussion and see if they'd be willing to provide stable access to the underlying websocket connection, and perhaps even provide an auto-generated API on top of it similar to chrome-debugging-client.

I will go ahead and open an issue on puppeteer and reference this RFC.

**Comment by krisselden** [comment]
I've switched to using the finders from chrome-launcher which is what lighthouse uses, puppeteer seems more automation focused than benchmarking, and enables a lot of events on various domains by default, that I'm going to keep maintaining this.
