### ISSUE TITLE
Intermittent "failed waiting for port file"

### ISSUE THREAD

**Issue by asakusuma** [devtrace/chrome-debugging-client#26]
I'd estimate this happens 1 out of every 50 times spawn browser is run in CI. Not sure if we should just increase the timeout from 2 seconds or if there is sometimes a legit problem finding the port file.
https://github.com/devtrace/chrome-debugging-client/blob/18b75ac62e088e15a87bc01835d61ef2032da437/lib/spawn-browser.ts#L28

**Comment by krisselden** [comment]
changed this to match what chromedriver does in #30
